package com.common.model;

import java.util.List;

import com.common.model.base.BasePagecache;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Pagecache extends BasePagecache<Pagecache> {
	public static final Pagecache dao = new Pagecache();
	
	public static List<Pagecache> findUntrackedPlayer(int maxNum){
		String sql = "SELECT * FROM `pagecache` where `status` = 0 ORDER BY createTime DESC limit ?";
		return dao.find(sql,maxNum);
	}
	public static Pagecache findPlayerByPlayerName(String playerName){
		return dao.findFirst("SELECT * FROM `pagecache` where playerName = ?",playerName);
	}
}
